### ISSUE TITLE
Continue sync where last stopped

### ISSUE THREAD

**Issue by scifi1** [mandarons/icloud-docker#195]
**Use case**
Would it be possible to implement a way for the application to restart sync where it last stopped?
I have 60 000+ files and one complete sync pass takes days (detecting and skipping one file consumes about 2 seconds)

I suppose it needs to be solution based on looping around a sequence of filters to chop up the complete sync task.
Maybe then restart sync using the last filter.

**Comment by mandarons** [comment]
Interaction with iCloud is polling based. The app needs to traverse the directory tree from its root to leaves to detect changes. Resuming the sync from where it stopped (due to error, timeout etc.) will only help with that iteration of tree traversal. It will not speed up next iteration as it must traverse the whole tree to detect changes.

However, current approach is serial - process one path and then move on to the next path. I am working on next-gen of this app which will be utilizing concurrency to significantly improve the performance.

**Comment by scifi1** [comment]
Hi, that would be awesome and worth waiting for!

Would it be possible to also add a feature such as a "one time" sync option suitable for cron-jobs?

**Comment by mandarons** [comment]
One time sync is currently available. Just set ```sync_interval``` to -1 to exit after sync.

**Comment by scifi1** [comment]
Cool, thanks!

**Comment by scifi1** [comment]
Thank you

**Comment by lostb1t** [comment]
@mandarons is there a branch available for the work going into concurrency?

**Comment by scifi1** [comment]
> @mandarons is there a branch available for the work going into concurrency?

I thought I would look into spinning up a bunch of containers, with the obvious drawback of multiple config files with different path expressions....Concurrency support would really be good..

**Comment by mandarons** [comment]
Concurrency work hasn't started yet for this project. I am currently working on making the library that is used by this app, concurrent [aioicloud](https://github.com/mandarons/aioicloud).
