### ISSUE TITLE
Docker Hub Tags latest/main mismatched

### ISSUE THREAD

**Issue by nicx** [mandarons/icloud-docker#39]
As you can see here https://hub.docker.com/r/mandarons/icloud-drive/tags there is a difference between "main" and "latest". I was struggeling about tha becaue I always use the "latest" flag, but in this case this was just not the newest/latest verison but an older one. Or in other words: "main" is newer than "latest" on docker hub ;)

Can you please correct this? Thanks :)

**Comment by mandarons** [comment]
@nicx that's correct and expected behavior. I have two types of releases on hub.docker.com - development and official. Development release is straight out of `main` branch of this repository. It is the work in progress and may not be stable to be used in production. It is a common practice to use branch name i.e. `main` in this case, as tag name for Docker image. 

If no tag is specified, Docker by default pulls `latest` tag. It is common practice for people who always want `latest` official release to not specify any tag in their `docker-compose` or `docker ...` commands. When they need to upgrade to latest official release, simply pulling the image without any tag does the trick. Hence, `latest` always points to most recent (or latest) official release.

Hope this helps. :)

**Comment by nicx** [comment]
@mandarons thanks for clarification. Until now I never heard of "main" is a develoment or unstable branch, therfore i;my experience main should be teh same as latest, and in addition there should bema development branch. But anyway... thanks again ;)
