### ISSUE TITLE
[FEATURE] Optionally pass password from environment variable

### ISSUE THREAD

**Issue by mandarons** [mandarons/icloud-docker#67]
**Use case**
As a user, I want to pass password through environment variable `ICLOUD_PASSWORD` so that I don't have to enter it manually.

**Describe the solution you'd like**
Ability to pass password through environment variable in container

**Describe alternatives you've considered**
Passing through `config.yaml`. Generally environment variables are considered as more secure than plain-text files.

**Additional context**
None

**Comment by markjgardner** [comment]
I ended up solving for this (partially) by using [icloud-photos-downloader](https://github.com/icloud-photos-downloader/icloud_photos_downloader) instead which supports feeding the credentials as arguments. This specifc solution is less secure and the general solution is a bit narrower scope than this project (photos only). My solution is [here](https://github.com/markjgardner/icloud-extractor).

I point this out, because icloudpd uses the same base library under the covers ([pycloud](https://github.com/picklepete/pyicloud))

**Comment by mandarons** [comment]
If you don't mind passing password as plain-text, you can use following command for login:
`docker exec -it icloud /bin/sh -c "icloud --username=<icloud-username> --password=<icloud-password>"`

If you have 2FA enabled, you will need to provide 2FA code manually though.
